document.getElementById('type-select').addEventListener('change', updateItems);
document.getElementById('item-select').addEventListener('change', updateActiveWork);

function updateItems() {
    const typeSelected = document.getElementById('type-select').value;
    const itemSelect = document.getElementById('item-select');
    itemSelect.innerHTML = '<option value="">Selecciona una opción</option>';
    if (typeSelected) {
        const uniqueValues = [...new Set(obras.map(item => item[typeSelected]))];
        uniqueValues.forEach(value => {
            const option = document.createElement('option');
            option.value = value;
            option.textContent = value;
            itemSelect.appendChild(option);
        });
    }
}

let previousSelectedParagraph = null;

function updateActiveWork() {
    let type = document.getElementById("type-select").value;
    let item = document.getElementById("item-select").value;
    let autocompleteSection = document.getElementById("autocomplete-container");
    
    let resultados = '';

    for (let i = 0; i < obras.length; i++) {
        if (obras[i][type] === item) {
            resultados += `<p>${obras[i].obra}</p>`;
        }
    }

    autocompleteSection.innerHTML = resultados || 'No se encontró la obra';

    
    let divContainer = document.getElementById('autocomplete-container')
    let paragraphs = divContainer.querySelectorAll('p');
    paragraphs.forEach((pTag) => {
        pTag.addEventListener('click', function() {
            executeFunction(pTag);
        });
    });
}

function executeFunction(pTag) {
    
    if (previousSelectedParagraph) {
        previousSelectedParagraph.classList.remove('active');
    }
    
    pTag.classList.add('active');
    
    previousSelectedParagraph = pTag;

    const result = obras.find(obra => obra.obra === pTag.textContent);
    
    if (result) {
        document.getElementById('data-water-basin').value = result.cuenca;
        document.getElementById('data-municipality').value = result.municipio;
        document.getElementById('data-entity').value = result.entidad;
        document.getElementById('data-social-movement').value = result.movimientoSocial;
        document.getElementById('data-exp').value = result.expediente;
        document.getElementById('data-reso').value = result.resolucion;
        document.getElementById('data-workers').value = result.trabajadores;
        document.getElementById('data-meters').value = result.metros;
		document.getElementById('iframe-map').src = result.hrefMap;
		document.getElementById('download-container').style.display = 'flex';
		document.getElementById('download-container').href = result.fichaCauce;
        
    } else {
        document.getElementById('data-water-basin').value = '';
        document.getElementById('data-municipality').value = '';
        document.getElementById('data-entity').value = '';
        document.getElementById('data-workers').value = '';
        document.getElementById('data-meters').value = '';
        document.getElementById('iframe-map').src = '';
		document.getElementById('download-container').style.display = 'none';
		document.getElementById('download-container').href = '';
    }
}

const obras = [		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento del Arroyo San Francisco aguas abajo',
		cuenca: 'Cuenca Arroyo San Francisco - Las Piedras',
		municipio: 'Almirante Brown',
		entidad: 'Asociación Civil La Fábrica',
		movimientoSocial: 'Movimiento Evita',
		expediente: 'EX-2024-09425717-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-563-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Daniel Amarilla',
		responsableCarga: 'Mario Miño',
		trabajadores: '20',
		metros: '3770',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1g-iT_84k6LdDe-PWtPXssP8BVdoAQbo&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1D-YBCj0ML8DQKpb5NV6qca-og7Xm8sTf/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento del Arroyo San Francisco aguas arriba',
		cuenca: 'Cuenca Arroyo San Francisco - Las Piedras',
		municipio: 'Almirante Brown',
		entidad: 'Asociación Civil La Fábrica',
		movimientoSocial: 'Movimiento Evita',
		expediente: 'EX-2024-09429076-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-664-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Daniel Amarilla',
		responsableCarga: 'Mario Miño',
		trabajadores: '20',
		metros: '3000',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1WfBheXQy3jyQyv40PA0wn5vykw2ilsc&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1ZymNqr4YibzBD5y8ElAZcq9ul4PuHPEs/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento del Arroyo del Rey y afluente',
		cuenca: 'Cuenca Río Matanza - Riachuelo',
		municipio: 'Almirante Brown',
		entidad: 'Cooperativa de Trabajo Néstor Kirchner Ltda.',
		movimientoSocial: 'Independiente',
		expediente: 'EX-2024-15806562-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-774-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Daniel Amarilla',
		responsableCarga: 'Mario Miño',
		trabajadores: '25',
		metros: '6600',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1e0_x7ldOks-QjAjbqw6Mzm_BrnqcCfA&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1mk6u_5L2Ipelm3oezqvfrIOzp7WcevUt/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento de los Canales Garibaldi, Espora, La Tijereta y Charcas',
		cuenca: 'Cuenca Arroyo San Francisco - Las Piedras',
		municipio: 'Almirante Brown',
		entidad: 'Cooperativa de Trabajo Nuevos Horizontes Ltda.',
		movimientoSocial: 'FECOOPBA',
		expediente: 'EX-2024-09501554-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-609-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Daniel Amarilla',
		responsableCarga: 'Mario Miño',
		trabajadores: '25',
		metros: '5700',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1pmiu2FX_ktL5QUk-Ia-nTXo2Z7rcLp8&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1GJbGoHSgG5aQ_4JlDWlk6Dolzc0_noy3/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento de los Canales pluviales del barrio Rayo de sol',
		cuenca: 'Cuenca Río Matanza - Riachuelo',
		municipio: 'Almirante Brown',
		entidad: 'Cooperativa de Trabajo Nuevos Horizontes Ltda.',
		movimientoSocial: 'FECOOPBA',
		expediente: 'EX-2024-09501604-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-592-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Daniel Amarilla',
		responsableCarga: 'Mario Miño',
		trabajadores: '30',
		metros: '4430',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1d0vMqj-FYT-3f4d1MmlIaIe1ySk-_kE&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1wQWOCv3R9rFsYiRcOvjqOh_j4pbk7XJP/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento del Arroyo Las Conchitas y su Afluente',
		cuenca: 'Cuenca Arroyo Las Conchitas',
		municipio: 'Berazategui',
		entidad: 'Cooperativa de Trabajo Fuerzas del Alma Ltda.',
		movimientoSocial: 'FECOOPBA',
		expediente: 'EX-2024-09884127-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-589-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Daniel Amarilla',
		responsableCarga: 'Silvia Guitián',
		trabajadores: '25',
		metros: '7300',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1ehE6W5zIZrb7piWPCtZf6TgIiGx-ivY&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1CQ9kx72Qjar7at_qsTds_KM_MvN4UTF4/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento del Arroyo Pereyra y su afluente',
		cuenca: 'Cuenca Arroyo Pereyra',
		municipio: 'Berazategui',
		entidad: 'Cooperativa de Trabajo Pacha Limpia Ltda.',
		movimientoSocial: 'Movimiento Evita',
		expediente: 'EX-2024-09501643-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-576-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Daniel Amarilla',
		responsableCarga: 'Silvia Guitián',
		trabajadores: '25',
		metros: '6310',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1t7RqMd5GP3Hlu4VjSCzrn5WtiX40C7I&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1jIjxj14INsF5JOl5qWP7h1862hucRkuP/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento del Arroyo San Juan y desagües de zona norte',
		cuenca: 'Cuenca Arroyo Jimenez',
		municipio: 'Berazategui',
		entidad: 'Cooperativa de Trabajo Pacha Limpia Ltda.',
		movimientoSocial: 'Movimiento Evita',
		expediente: 'EX-2024-09501757-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-607-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Daniel Amarilla',
		responsableCarga: 'Silvia Guitián',
		trabajadores: '25',
		metros: '5800',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1hTXIufwxjce_AKlNAlPawe34Dvpsl_A&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1S51ArG7LXvungFraFKLdNj-G5vvQtSF_/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento del Arroyo Saladero y su afluente',
		cuenca: 'Área de bañados',
		municipio: 'Berisso',
		entidad: 'Cooperativa de Trabajo El Hornero Comunitario Ltda.',
		movimientoSocial: 'PSF',
		expediente: 'EX-2024-10204359-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-610-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Mariano Losardo',
		responsableCarga: 'Gustavo Gómez',
		trabajadores: '25',
		metros: '4970',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1uB0J_3IAgJ-p2buBscNBihiDOMVwva8&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/15zozqcZt0krspyHPZ8KcN3opug5H8ZNS/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento del Arroyo Gonzalez y Afluentes en la localidad de Jeppener',
		cuenca: 'Cuenca Río Samborombón',
		municipio: 'Brandsen',
		entidad: 'Cooperativa de Trabajo Primero Brandsen Ltda.',
		movimientoSocial: 'Frente Grande',
		expediente: 'EX-2024-08787968-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-646-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Mariano Losardo',
		responsableCarga: 'Gustavo Gómez',
		trabajadores: '25',
		metros: '5700',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1osLaVEBNnWNyUqCdo3arernes10m7nI&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1R7UJ5PXtc89WKMNSfNcwgBUqFxyHa1KP/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento del Canal Aleluya y Zanjón Alfonsina Storni',
		cuenca: 'Cuenca Río Samborombón',
		municipio: 'Brandsen',
		entidad: 'Cooperativa de Trabajo Somos Brandseños Ltda.',
		movimientoSocial: 'FECOOPBA',
		expediente: 'EX-2024-10318949-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-614-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Mariano Losardo',
		responsableCarga: 'Gustavo Gómez',
		trabajadores: '26',
		metros: '4800',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=13kZC_JC0vThSKGZOOBWN2jMwxhrOjjM&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1eEoudSJTzDZELcaSpHbHi7EOLKfmPpw0/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento del Canal Belgrano y del Zanjón Córdoba',
		cuenca: 'Cuenca Río Samborombón',
		municipio: 'Brandsen',
		entidad: 'Cooperativa de Trabajo Somos Brandseños Ltda.',
		movimientoSocial: 'FECOOPBA',
		expediente: 'EX-2024-10320005-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-616-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Mariano Losardo',
		responsableCarga: 'Gustavo Gómez',
		trabajadores: '28',
		metros: '3870',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1L0dgqfP1OOYDBMhMXYoLVSaZWrhOgC4&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1C9-NBzn102aKb3sVK0DUieROPtYMKcrK/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento de los canales en Ingeniero Otamendi, prolongación de Av. Ameghino y afluentes del Arroyo Santa Cruz',
		cuenca: 'Cuenca Río Luján',
		municipio: 'Campana',
		entidad: 'Cooperativa de Trabajo Nuevo Cambio Ltda.',
		movimientoSocial: 'Independiente',
		expediente: 'EX-2024-09778443-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-636-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Darío Astegiano',
		responsableCarga: 'Victor Banegas',
		trabajadores: '40',
		metros: '5550',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1YxlWr075Bym5cWZJq3SUekgHDGn6CAw&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1uful-L0TDsSHkyVZIDcOhV26FRyA026B/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento del Afluente del Arroyo Valdez en zona norte',
		cuenca: 'Cuenca Río Salado',
		municipio: 'Chascomús',
		entidad: 'Cooperativa de Trabajo Nuevos Horizontes Ltda.',
		movimientoSocial: 'FECOOPBA',
		expediente: 'EX-2024-09501512-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-574-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Pablo Steinbach',
		responsableCarga: 'Pablo Steinbach',
		trabajadores: '25',
		metros: '4700',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=11jIoOEKkPoxkGxkfu1O1iGYhtHerKec&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1hqn0frbD_y65pdR-STCANPxYD_aMxzWS/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento del Arroyo Los Toldos y afluente',
		cuenca: 'Cuenca Río Salado',
		municipio: 'Chascomús',
		entidad: 'Cooperativa de Trabajo Nuevos Horizontes Ltda.',
		movimientoSocial: 'FECOOPBA',
		expediente: 'EX-2024-09501483-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-634-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Pablo Steinbach',
		responsableCarga: 'Pablo Steinbach',
		trabajadores: '25',
		metros: '4900',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1qPUNiLpH6C6X0KVYW83UyuduuIfwSLA&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1dYCSkCMGizSiHh9dKuQ7WEPgQNgH7ZRM/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento del Arroyo San Felipe y costa de laguna',
		cuenca: 'Cuenca Río Salado',
		municipio: 'Chascomús',
		entidad: 'Cooperativa de Trabajo Nuevos Horizontes Ltda.',
		movimientoSocial: 'FECOOPBA',
		expediente: 'EX-2024-09501415-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-649-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Pablo Steinbach',
		responsableCarga: 'Pablo Steinbach',
		trabajadores: '25',
		metros: '4800',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1KPoTnVSklbHCH6S_MQJBWGAo3BtGHyc&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1z5FPywhJpe6MiYdc27jaK-Pe0LYJkWDb/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento del Arroyo Doña Flora y su afluente y los canales Barragán y de Zona Franca',
		cuenca: 'Área de bañados',
		municipio: 'Ensenada',
		entidad: 'Cooperativa de Trabajo La Morita Ltda.',
		movimientoSocial: 'FECOOPBA',
		expediente: 'EX-2024-09443376-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-606-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Mariano Losardo',
		responsableCarga: 'Gustavo Gómez',
		trabajadores: '25',
		metros: '6400',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1QGsrgKSfjJHF0Ia3SKTukMI7ky1OeTE&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/199jQyw-K9I1EVPCbI_xKW_v6F28xP5X0/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento de los Arroyos Bedoya, Saboya y Los Pinos y el afluente del Arroyo Garín',
		cuenca: 'Cuenca Río Luján',
		municipio: 'Escobar',
		entidad: 'Cooperativa de Trabajo Che Guevara Ltda.',
		movimientoSocial: 'Barrios de Pie',
		expediente: 'EX-2024-09283382-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-624-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Darío Astegiano',
		responsableCarga: 'Victor Banegas',
		trabajadores: '25',
		metros: '6750',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1IerT4dg-VAgu3MhyfRiHtRf83vE7ZHE&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1U6k9kXa77Fph46EE7DtkuYg34msExrr0/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento del Arroyo Loma Verde',
		cuenca: 'Cuenca Río Luján',
		municipio: 'Escobar',
		entidad: 'Cooperativa de Trabajo La Plebeya Ltda.',
		movimientoSocial: 'Quebracho',
		expediente: 'EX-2024-10220862-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-622-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Darío Astegiano',
		responsableCarga: 'Victor Banegas',
		trabajadores: '25',
		metros: '3800',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=15dzWgd9G41cXrd1QCCWwd8H8lpjjw6M&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1vZNNTiWGW4Tm34ZhTeS0jsC41HaeKZvO/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento del Arroyo Garín',
		cuenca: 'Cuenca Río Luján',
		municipio: 'Escobar',
		entidad: 'Cooperativa de Trabajo Nuevo Cambio Ltda.',
		movimientoSocial: 'Independiente',
		expediente: 'EX-2024-09687561-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-587-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Darío Astegiano',
		responsableCarga: 'Victor Banegas',
		trabajadores: '25',
		metros: '5240',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1G3mXdXkR0gxYN98Y_4Op4kDn4P4Pu9w&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1LMRcPoKEYgWExfaEgKdXrlByzT3nvBoa/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento de los Arroyos Medrano, El Triángulo, Ortega y Santa Catalina',
		cuenca: 'Cuenca Río Matanza - Riachuelo',
		municipio: 'Esteban Echeverría',
		entidad: 'Cooperativa de Trabajo La Morita Ltda.',
		movimientoSocial: 'FECOOPBA',
		expediente: 'EX-2024-09452727-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-579-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Mario Ferreyra',
		responsableCarga: 'Valeria Figueroa',
		trabajadores: '25',
		metros: '6385',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1Z6rEUVcHJJdC1OtLTg_SjNueN7-kZXk&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1LhD_8jBZABsZtmsHcT7NY4yyetPvxW6-/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento de los Arroyos Aguirre y Rossi',
		cuenca: 'Cuenca Río Matanza - Riachuelo',
		municipio: 'Ezeiza',
		entidad: 'Cooperativa de Trabajo Las Colinas Ltda.',
		movimientoSocial: 'FECOOPBA',
		expediente: 'EX-2024-09416324-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-662-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Javier Chioccariello',
		responsableCarga: 'Gustavo Gómez',
		trabajadores: '25',
		metros: '5000',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1VMwcQs2Nv0bAHCRAsZay1G_e2xxBd9U&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1YJgejcIF6XoOpkO8pT3aa6i1kG95iezS/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento de los Canales Cortez y Vista Alegre',
		cuenca: 'Cuenca Río Matanza - Riachuelo',
		municipio: 'Ezeiza',
		entidad: 'Cooperativa de Trabajo Las Colinas Ltda.',
		movimientoSocial: 'FECOOPBA',
		expediente: 'EX-2024-09415916-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-645-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Javier Chioccariello',
		responsableCarga: 'Gustavo Gómez',
		trabajadores: '25',
		metros: '6200',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1rX5I4soE6taZY4SaZwvaHzkHLIu01BY&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1OVYDn4UPwzkKcUNRYr0Bb7sd6RLzyg5Q/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento de los Arroyos del Gato y Aguirre y su afluente',
		cuenca: 'Cuenca Río Matanza - Riachuelo',
		municipio: 'Ezeiza',
		entidad: 'Cooperativa de Trabajo Virgen del Luján Ltda.',
		movimientoSocial: 'Independiente',
		expediente: 'EX-2024-09283725-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-666-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Javier Chioccariello',
		responsableCarga: 'Gustavo Gómez',
		trabajadores: '25',
		metros: '4700',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1aDkWD4FjQpr6aZNve0JBiXvMDViZfCQ&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1Npqnvei5EeMXLiKNXTuLXrgftn2Xh5bY/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento del Arroyo Las Conchitas',
		cuenca: 'Cuenca Arroyo Las Conchitas',
		municipio: 'Florencio Varela',
		entidad: 'Cooperativa de Trabajo Evita 4 Ltda.',
		movimientoSocial: 'Movimiento Evita',
		expediente: 'EX-2024-09423434-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-667-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Daniel Amarilla',
		responsableCarga: 'Mario Miño',
		trabajadores: '20',
		metros: '6000',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1pk-rjaF9pRs2Xf7Z9QaHv7244gHZAx4&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1LVHxnp2ppYY_727sY-pGoPLvrt_j5dO1/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento del Arroyo San Juan',
		cuenca: 'Cuenca Arroyo Jimenez',
		municipio: 'Florencio Varela',
		entidad: 'Cooperativa de Trabajo Evita 4 Ltda.',
		movimientoSocial: 'Movimiento Evita',
		expediente: 'EX-2024-09425654-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-663-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Daniel Amarilla',
		responsableCarga: 'Mario Miño',
		trabajadores: '20',
		metros: '3000',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1UTDqF4osx2W48X7CN4DVw7a8LXskziI&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1K_dhq54JIvNLs8e1dzmRdv2Tjo4od2tO/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento de los Arroyos La Tapera y El Cardalito y el Canal de desagüe pluvial del barrio Nuevo Golf',
		cuenca: 'Cuenca de los Arroyos La Tapera, Santa Elena, Seco',
		municipio: 'General Pueyrredón',
		entidad: 'Cooperativa de Trabajo Nuevos Horizontes Ltda.',
		movimientoSocial: 'FECOOPBA',
		expediente: 'EX-2024-09501315-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-602-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Pablo Steinbach',
		responsableCarga: 'Pablo Steinbach',
		trabajadores: '25',
		metros: '3600',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1pNlLqdkc5lvL16KPnAmGYlIdIqkRSdQ&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1Gzxrm62DdSKKWF1duQnCcmJElvn8znLT/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento del Arroyo Corrientes y Afluentes',
		cuenca: 'Cuenca de los Arroyos Lobería y Corrientes',
		municipio: 'General Pueyrredón',
		entidad: 'Cooperativa de Trabajo Nuevos Horizontes Ltda.',
		movimientoSocial: 'FECOOPBA',
		expediente: 'EX-2024-09501367-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-639-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Pablo Steinbach',
		responsableCarga: 'Pablo Steinbach',
		trabajadores: '30',
		metros: '7450',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1tdk8RNC6VSCKspA9hW6N8SARGRFyAfQ&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1DSuhcvfW2oMcLm6znGCOhW4I2OPLNjTT/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento de los Arroyos El Carpincho, Parque Granadero y los canales de Planta Urbana y Horacio Quiroga',
		cuenca: 'Cuenca Río Reconquista',
		municipio: 'General Rodríguez',
		entidad: 'Cooperativa de Trabajo Evita Compañera Ltda.',
		movimientoSocial: 'Independiente',
		expediente: 'EX-2024-08761266-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-625-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Mario Ferreyra',
		responsableCarga: 'Valeria Figueroa',
		trabajadores: '25',
		metros: '5920',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1akg1fx61sghlDenviDe64gJUBqMblug&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/19ZP1BJQl8c2STIyAhRvaVeWJLR3KbPb9/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento del Arroyo Las Catonas',
		cuenca: 'Cuenca Río Reconquista',
		municipio: 'General Rodríguez',
		entidad: 'Cooperativa de Trabajo Fuerzas del Alma Ltda.',
		movimientoSocial: 'FECOOPBA',
		expediente: 'EX-2024-09883763-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-588-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Mario Ferreyra',
		responsableCarga: 'Leonardo Ruiz',
		trabajadores: '25',
		metros: '4830',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1Pwqtg-Da-L3Wq2kEJKL63Tt1eGGGRXQ&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1ZtBzwpPdXDlnD6uumEYC0TV65TuCW6oC/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento de la Cañada San Antonio Brazo Corto y Canal Ricardo Balbin',
		cuenca: 'Cuenca Río Reconquista',
		municipio: 'General Rodríguez',
		entidad: 'Cooperativa de Trabajo La Gaviota Ltda.',
		movimientoSocial: 'FECOOPBA',
		expediente: 'EX-2024-08751217-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-651-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Mario Ferreyra',
		responsableCarga: 'Leonardo Ruiz',
		trabajadores: '25',
		metros: '6525',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1Ij5U18px3OakN_esHdSez7cbVLcOGH0&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1FvV9sHOgMWJ210MqvyXKBKm323QeRiKm/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento de la Cañada San Antonio Brazo Largo',
		cuenca: 'Cuenca Río Reconquista',
		municipio: 'General Rodríguez',
		entidad: 'Cooperativa de Trabajo La Gaviota Ltda.',
		movimientoSocial: 'FECOOPBA',
		expediente: 'EX-2024-08747706-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-618-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Mario Ferreyra',
		responsableCarga: 'Leonardo Ruiz',
		trabajadores: '25',
		metros: '7500',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1NXF7E54gnJ08B4bIc3PJtK0RvlZca0c&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1__kYQXx5Mt-ZcyuLBCYsNTg3ljCqwiQF/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento de la Cañada Álvarez',
		cuenca: 'Cuenca Río Reconquista',
		municipio: 'General Rodríguez',
		entidad: 'Cooperativa de Trabajo Los Horneros Ltda.',
		movimientoSocial: 'Corriente Nacional y Popular',
		expediente: 'EX-2024-09882621-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-665-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Mario Ferreyra',
		responsableCarga: 'Leonardo Ruiz',
		trabajadores: '25',
		metros: '4400',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1LyKd2uRkFObORWnNp8Xubhgfi3t_8Nw&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1LWu7Ec_ucoM6xyGiwqBjeReVIXWEGxiu/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento de los afluentes del Arroyo Las Chozas',
		cuenca: 'Cuenca Río Reconquista',
		municipio: 'General Rodríguez',
		entidad: 'Cooperativa de Trabajo Los Horneros Ltda.',
		movimientoSocial: 'Corriente Nacional y Popular',
		expediente: 'EX-2024-12916063-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-661-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Mario Ferreyra',
		responsableCarga: 'Leonardo Ruiz',
		trabajadores: '25',
		metros: '5780',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1MavETonXty3-qunf2egJ_k4sBlyKfZM&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1_qN78DekZczIdkelC3x85-kwI2VxJRYE/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento de los Canales José León Suárez Norte, Esmeralda y afluentes de calle San Martín y paralelo a Au. Camino del Buen Ayre',
		cuenca: 'Cuenca Río Reconquista',
		municipio: 'General San Martín',
		entidad: 'Cooperativa de Trabajo 9 de Julio Ltda. (GSM)',
		movimientoSocial: 'Movimiento Evita',
		expediente: 'EX-2024-09279151-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-637-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Juan Maglione',
		responsableCarga: 'Juan Barroca',
		trabajadores: '25',
		metros: '3130',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1iSnB6RWpqxuxeNjNj4oN7LHYkHG7vcI&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1BA6nZGkfBh_j_eraGdcTqdOOnh0q1fbV/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento de los Canales de calle 135, José Ingenieros y Eva Perón',
		cuenca: 'Cuenca Río Reconquista',
		municipio: 'General San Martín',
		entidad: 'Cooperativa de Trabajo Che Guevara Ltda.',
		movimientoSocial: 'Barrios de Pie',
		expediente: 'EX-2024-09283304-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-578-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Juan Maglione',
		responsableCarga: 'Juan Barroca',
		trabajadores: '25',
		metros: '3880',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=18KE5HqIDbjEozoiaW_Md8wz9LrWnaoc&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1u2XpPj8i6eFfegYBW-9eZUXfppqXywvY/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento del Arroyo Soto',
		cuenca: 'Cuenca Río Reconquista',
		municipio: 'Hurlingham',
		entidad: 'Cooperativa de Trabajo El Hornero Comunitario Ltda.',
		movimientoSocial: 'PSF',
		expediente: 'EX-2024-10182586-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-569-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Antonella Morelli',
		responsableCarga: 'Mayra Guevara',
		trabajadores: '25',
		metros: '5800',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1P7i2ELJU3A8T_KjBMN40fvZTUoiADE8&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1yv3HOl2dspA-U6ImZ1Atcn697YGesLnS/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento del Arroyo Pinazo',
		cuenca: 'Cuenca Río Luján',
		municipio: 'José C. Paz',
		entidad: 'Cooperativa de Trabajo Proyectando Juntos Ltda.',
		movimientoSocial: 'FECOOPBA',
		expediente: 'EX-2024-09463001-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-566-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Juan Maglione',
		responsableCarga: 'Iván Orellana',
		trabajadores: '25',
		metros: '4160',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1JWY5qFDqxr4ybgRIB1BbHrpe6FIScco&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1Tkak401Hsi8bubRNk-sNV5aYTI7fbUGW/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento del Arroyo Zinny aguas abajo y canal Beláustegui',
		cuenca: 'Cuenca Río Luján',
		municipio: 'José C. Paz',
		entidad: 'Cooperativa de Trabajo Sueños Paceños Ltda.',
		movimientoSocial: 'FECOOPBA',
		expediente: 'EX-2024-09464229-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-584-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Juan Maglione',
		responsableCarga: 'Iván Orellana',
		trabajadores: '25',
		metros: '5380',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1wYWDNIHfCZKopu426KgaccQS7kiCbmY&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1yXg47iWByuH0m3hwSR8OCJZPB9B8EIYV/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento del Arroyo Zinny aguas arriba y canal de Panamá',
		cuenca: 'Cuenca Río Luján',
		municipio: 'José C. Paz',
		entidad: 'Cooperativa de Trabajo Sueños Paceños Ltda.',
		movimientoSocial: 'FECOOPBA',
		expediente: 'EX-2024-09473435-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-656-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Juan Maglione',
		responsableCarga: 'Iván Orellana',
		trabajadores: '25',
		metros: '5700',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1F1sMMx7Qyt4vO7QRKfGmrvNNJjH2_-E&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1YmvJFWFG6yiWsq6g5Ab8vMzWUe8UOCmr/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento de los Arroyos Morales y Las Víboras y los canales de desagüe del Barrio Nicole',
		cuenca: 'Cuenca Río Matanza - Riachuelo',
		municipio: 'La Matanza',
		entidad: 'Cooperativa de Trabajo Cada día un Sueño Ltda.',
		movimientoSocial: 'Barrios de Pie',
		expediente: 'EX-2024-10330777-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-694-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Javier Chioccariello',
		responsableCarga: 'Teresa Colman',
		trabajadores: '32',
		metros: '7280',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1OWuWbSazSY8MFnlAXj6AsSIFsF3hUBQ&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1nsyxjhr0SDKWX3Sa1qvdVxWzYC9dzeNx/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento del Arroyo Morales y afluentes y el canal Apipé',
		cuenca: 'Cuenca Río Matanza - Riachuelo',
		municipio: 'La Matanza',
		entidad: 'Cooperativa de Trabajo Cada día un Sueño Ltda.',
		movimientoSocial: 'Barrios de Pie',
		expediente: 'EX-2024-09282367-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-686-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Javier Chioccariello',
		responsableCarga: 'Teresa Colman',
		trabajadores: '32',
		metros: '6950',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1dzTSdqR-niDoaRtMEia1W8ChXZnUrOQ&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1cFOFdj_durXMf7XLC3Na6eBeHa8y7DUP/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento del Arroyo Dupi',
		cuenca: 'Cuenca Río Matanza - Riachuelo',
		municipio: 'La Matanza',
		entidad: 'Cooperativa de Trabajo Fuerzas del Alma Ltda.',
		movimientoSocial: 'FECOOPBA',
		expediente: 'EX-2024-09884735-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-590-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Javier Chioccariello',
		responsableCarga: 'Teresa Colman',
		trabajadores: '35',
		metros: '2450',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1ltjxaLd_iXOBuMr4b8Y6qtf2-jbw1XY&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1Bfv3SF8YFcfCPPprU8lEGhc3xnYT1xMN/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento de los Arroyos Susana y Don Mario y sus afluentes',
		cuenca: 'Cuenca Río Matanza - Riachuelo',
		municipio: 'La Matanza',
		entidad: 'Cooperativa de Trabajo La Gaviota Ltda.',
		movimientoSocial: 'FECOOPBA',
		expediente: 'EX-2024-08776049-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-621-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Javier Chioccariello',
		responsableCarga: 'Teresa Colman',
		trabajadores: '25',
		metros: '3960',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1u1C0rAcznAxqE_jimnF0-0IEO9Z7U3U&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1WZDMZDkR8k5AkUQ0xIK8J55IH7WVHQ3W/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento de los Arroyos Susana y Dupi y los zanjones García Merou y de la Fuente',
		cuenca: 'Cuenca Río Matanza - Riachuelo',
		municipio: 'La Matanza',
		entidad: 'Cooperativa de Trabajo La Gaviota Ltda.',
		movimientoSocial: 'FECOOPBA',
		expediente: 'EX-2024-08772102-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-644-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Javier Chioccariello',
		responsableCarga: 'Teresa Colman',
		trabajadores: '25',
		metros: '3400',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1F1cymQLMq6BRSLytE8ZZex3nTWimaik&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1Jx8A3OMZXFZhFaRwkoEY4JWLw5VKGuL5/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento del Arroyo Dupi y afluente Iguazú',
		cuenca: 'Cuenca Río Matanza - Riachuelo',
		municipio: 'La Matanza',
		entidad: 'Cooperativa de Trabajo La Gaviota Ltda.',
		movimientoSocial: 'FECOOPBA',
		expediente: 'EX-2024-08741478-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-678-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Javier Chioccariello',
		responsableCarga: 'Teresa Colman',
		trabajadores: '25',
		metros: '4865',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=14hsyqXO5ZsU9e2SRrlA9cj_8Y9YIhnc&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1csEk0fnWVLlb54B5VW10DcI3aVqxHGDM/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento del Arroyo Garibaldi y afluentes, canales de desagüe del Barrio Garibaldi y paseo del Arroyo El Pescado',
		cuenca: 'Área de bañados',
		municipio: 'La Plata',
		entidad: 'Cooperativa de Trabajo 3 de Diciembre Ltda.',
		movimientoSocial: 'Independiente',
		expediente: 'EX-2024-08725621-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-642-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Mariano Losardo',
		responsableCarga: 'Camilo Smittenaar',
		trabajadores: '25',
		metros: '7000',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1bQ8bJboNaDi--WrpqUGPrbK9vGHv0NY&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1KnGhfDeBf0cRf-FeNtXwynlr81sFg6cs/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento del Arroyo Rodríguez desde 28 hasta 141, Arroyo Don Carlos desde 185 hasta 189 y zanjón paralelo a calle 486',
		cuenca: 'Cuenca Arroyos Rodríguez y Don Carlos',
		municipio: 'La Plata',
		entidad: 'Cooperativa de Trabajo 3 de Diciembre Ltda.',
		movimientoSocial: 'Independiente',
		expediente: 'EX-2024-09689034-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-608-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Mariano Losardo',
		responsableCarga: 'Camilo Smittenaar',
		trabajadores: '25',
		metros: '4660',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1SGgekCZ5USp2CjVEBB4ihaj_d0Dwj6Y&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1PiiS4va-0b3y1fEPBsL_JZMWpp7WTxv6/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento del Arroyo San Juan y afluentes del Arroyo Carnaval',
		cuenca: 'Cuenca Arroyo Pereyra',
		municipio: 'La Plata',
		entidad: 'Cooperativa de Trabajo 3 de Diciembre Ltda.',
		movimientoSocial: 'Independiente',
		expediente: 'EX-2024-09692607-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-647-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Mariano Losardo',
		responsableCarga: 'Camilo Smittenaar',
		trabajadores: '25',
		metros: '4800',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1wSN6hA0hQJnVB3vhngjFqR3YjsHRtsE&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1RPdWMXAT5DK9qgEETFjgBWU779nPgDhj/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento del Arroyo El Gato y afluentes en las localidades de Gonnet y Ringuelet',
		cuenca: 'Cuenca Arroyo El Gato',
		municipio: 'La Plata',
		entidad: 'Cooperativa de Trabajo Almagro Ltda.',
		movimientoSocial: 'PSF',
		expediente: 'EX-2024-08724892-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-655-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Mariano Losardo',
		responsableCarga: 'Camilo Smittenaar',
		trabajadores: '25',
		metros: '7100',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=194pv0L_akEFi1bUJ31SW8E9N05xuzNs&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1sjxbW1O_T-lceek1BkTpqo_KuTqv17Lt/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento del Arroyo El Gato y afluentes en Melchor Romero y Lisandro Olmos',
		cuenca: 'Cuenca Arroyo El Gato',
		municipio: 'La Plata',
		entidad: 'Cooperativa de Trabajo Almagro Ltda.',
		movimientoSocial: 'PSF',
		expediente: 'EX-2024-10838164-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-641-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Mariano Losardo',
		responsableCarga: 'Camilo Smittenaar',
		trabajadores: '30',
		metros: '9000',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1v-G9lw8NogCvvk2fxTZhJyKcmiuU1lo&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1sDCg6l0NQezrb5POHzhvKlzBNmmvVEkY/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento del Tramo inferior del Arroyo El Gato',
		cuenca: 'Cuenca Arroyo El Gato',
		municipio: 'La Plata',
		entidad: 'Cooperativa de Trabajo Almagro Ltda.',
		movimientoSocial: 'PSF',
		expediente: 'EX-2024-08725293-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-653-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Mariano Losardo',
		responsableCarga: 'Camilo Smittenaar',
		trabajadores: '25',
		metros: '5000',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=199fEpWR1mdQ3tikXNXX3PCUs1BoY_N4&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1rwUcnPm-f-c4SC2vFrp24KXmOZF1xK85/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento del Arroyo Regimiento y su afluente',
		cuenca: 'Cuenca Arroyo El Gato',
		municipio: 'La Plata',
		entidad: 'Cooperativa de Trabajo Amasando Sueños Ltda.',
		movimientoSocial: 'Movimiento Evita',
		expediente: 'EX-2024-09501887-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-583-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Mariano Losardo',
		responsableCarga: 'Camilo Smittenaar',
		trabajadores: '25',
		metros: '4245',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1xvtCEs1BAwitxyBYD6jYq0GaPqy6drs&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1B-0pz1mVutb54TtbMRd8Iv9tMnBN5wb5/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento de los Arroyos Martín y Carnaval',
		cuenca: 'Cuenca Arroyos Martín y Carnaval',
		municipio: 'La Plata',
		entidad: 'Cooperativa de Trabajo Argentina Resiste Ltda.',
		movimientoSocial: 'FECOOPBA',
		expediente: 'EX-2024-09279039-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-706-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Mariano Losardo',
		responsableCarga: 'Camilo Smittenaar',
		trabajadores: '25',
		metros: '10600',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=18j-khS5Gq3xGSDmf_MCC5LSUB4XdWPs&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1MqGNgyK5-7SWmv-4njaiIM49y4BQTKlE/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento del Arroyo Pérez y afluentes',
		cuenca: 'Cuenca Arroyo El Gato',
		municipio: 'La Plata',
		entidad: 'Cooperativa de Trabajo Argentina Resiste Ltda.',
		movimientoSocial: 'FECOOPBA',
		expediente: 'EX-2024-09280412-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-722-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Mariano Losardo',
		responsableCarga: 'Camilo Smittenaar',
		trabajadores: '25',
		metros: '7640',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1FlG6XP3ANuS1nzgA1IwIrrDKalOHXGQ&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1ZKwBbP05M-3_hf58kuKzfMAsZ1M-WV8e/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento de los Arroyos Don Carlos y Rodríguez',
		cuenca: 'Cuenca Arroyos Rodríguez y Don Carlos',
		municipio: 'La Plata',
		entidad: 'Cooperativa de Trabajo Los Kokitos Ltda.',
		movimientoSocial: 'FECOOPBA',
		expediente: 'EX-2024-09417411-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-640-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Mariano Losardo',
		responsableCarga: 'Camilo Smittenaar',
		trabajadores: '25',
		metros: '7640',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1SMkQIHlbTMWx0x9-C7k8PEyBgTrsmI8&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1OADIsSkzd5qB2FFX39UHRwfpGtkQwA3q/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento del Arroyo Maldonado y su Afluente en Barrio Monasterio',
		cuenca: 'Cuenca Arroyo Maldonado',
		municipio: 'La Plata',
		entidad: 'Cooperativa de Trabajo Los Kokitos Ltda.',
		movimientoSocial: 'FECOOPBA',
		expediente: 'EX-2024-09417887-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-643-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Mariano Losardo',
		responsableCarga: 'Camilo Smittenaar',
		trabajadores: '25',
		metros: '11100',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1GWLll204LrN0mLlg8RpbXqcC18mQIX4&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1o3aeM06ytnaBHTBTmxFtldGuDPnWoehS/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento del Tramo superior del Arroyo El Gato y Afluentes 2 y 3',
		cuenca: 'Cuenca Arroyo El Gato',
		municipio: 'La Plata',
		entidad: 'Cooperativa de Trabajo Néstor Vive en Nosotros Ltda.',
		movimientoSocial: 'FECOOPBA',
		expediente: 'EX-2024-09692369-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-654-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Mariano Losardo',
		responsableCarga: 'Camilo Smittenaar',
		trabajadores: '25',
		metros: '10300',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1X-KEL4F4ob2L5xXtzUPhE3iFBpk9SIM&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1bVLqvPLKDJKdc48AXGxYTeT23DEneLve/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento del Arroyo Carnaval y Afluente',
		cuenca: 'Cuenca Arroyos Martín y Carnaval',
		municipio: 'La Plata',
		entidad: 'Cooperativa de Trabajo Nuevo Cambio Ltda.',
		movimientoSocial: 'Independiente',
		expediente: 'EX-2024-09688238-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-595-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Mariano Losardo',
		responsableCarga: 'Camilo Smittenaar',
		trabajadores: '25',
		metros: '8500',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1lGP2A--ZAVAH5qan3NQ9PxFl7fceL7M&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1aE5njPAqAiyhIK-XZi31ChrBByKfMwcl/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento del Cauce Viejo del Arroyo del Rey',
		cuenca: 'Cuenca Río Matanza - Riachuelo',
		municipio: 'Lomas de Zamora',
		entidad: 'Cooperativa de Trabajo 9 de Julio Ltda. (LDZ)',
		movimientoSocial: 'Movimiento Evita',
		expediente: 'EX-2024-10176908-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-620-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Antonella Morelli',
		responsableCarga: 'Julia Palacio',
		trabajadores: '25',
		metros: '1770',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1xOZ1-a9GvWLNc-4xO5bBz4xIuZM50-c&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1s0bmSqA9Rmi27aZSZ_rtp-wN-qt6tqMz/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento del Arroyo del Rey',
		cuenca: 'Cuenca Río Matanza - Riachuelo',
		municipio: 'Lomas de Zamora',
		entidad: 'Cooperativa de Trabajo Cada día un Sueño Ltda.',
		movimientoSocial: 'Barrios de Pie',
		expediente: 'EX-2024-09281874-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-741-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Antonella Morelli',
		responsableCarga: 'Julia Palacio',
		trabajadores: '32',
		metros: '4360',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1c6Cpv4DmWZ38vNy_rjpWlGrTsLXgOJ0&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1xVX562_2CtHuRzwj4u9G7g62GO9vHyFY/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento del Arroyo Las Horquetas',
		cuenca: 'Cuenca Río Reconquista',
		municipio: 'Malvinas Argentinas',
		entidad: 'Cooperativa de Trabajo Las Colinas Ltda.',
		movimientoSocial: 'FECOOPBA',
		expediente: 'EX-2024-09417333-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-603-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Mario Ferreyra',
		responsableCarga: 'Valeria Figueroa',
		trabajadores: '25',
		metros: '6500',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=18kTtVKsKrd36kOv0H7tcM3Q50QXAVQ8&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1_qCBwy0dPhBVn80bjc-6NrYOy673gD3h/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento del Arroyo Las Tunas',
		cuenca: 'Cuenca Río Reconquista',
		municipio: 'Malvinas Argentinas',
		entidad: 'Cooperativa de Trabajo Las Colinas Ltda.',
		movimientoSocial: 'FECOOPBA',
		expediente: 'EX-2024-09416976-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-650-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Mario Ferreyra',
		responsableCarga: 'Valeria Figueroa',
		trabajadores: '25',
		metros: '4600',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1buhFaulSPd4t3e6Q_yFwPxI171KlvNU&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1p4kQux8brqo7BECjY_e6vadNXqnpKGnz/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento de los Arroyos Cuzco, Claro y Albuera',
		cuenca: 'Cuenca Río Luján',
		municipio: 'Malvinas Argentinas',
		entidad: 'Cooperativa de Trabajo Somos Nosotros Ltda.',
		movimientoSocial: 'FECOOPBA',
		expediente: 'EX-2024-10227874-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-580-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Mario Ferreyra',
		responsableCarga: 'Valeria Figueroa',
		trabajadores: '30',
		metros: '7260',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1dIuJ_BM8uzGr-Shs72tHQM8T8OuOL30&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/17l10xtMg5vMLAl_s5Ey8zGUQwdmc2e88/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento del Arroyo Gregorio de Laferrere y Afluente Bustillo',
		cuenca: 'Cuenca Río Reconquista',
		municipio: 'Merlo',
		entidad: 'Cooperativa de Trabajo Cada día un Sueño Ltda.',
		movimientoSocial: 'Barrios de Pie',
		expediente: 'EX-2024-09283486-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-688-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Antonella Morelli',
		responsableCarga: 'Julia Palacio',
		trabajadores: '25',
		metros: '3023',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1VKYn2MCDk-T0mxwhMRgtujvM3vocxMM&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/17lAW4skX58PFOBamuulbXWnkWnQKfyWW/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento de los Arroyos Saladero, Granadero, y El Trébol',
		cuenca: 'Cuenca Río Reconquista',
		municipio: 'Merlo',
		entidad: 'Cooperativa de Trabajo Mi Cielo Ltda.',
		movimientoSocial: 'FECOOPBA',
		expediente: 'EX-2024-09737927-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-565-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Antonella Morelli',
		responsableCarga: 'Mayra Guevara',
		trabajadores: '30',
		metros: '5850',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1f_eSjrPtyEJ_vIFxxK6PNyVoUQnjC3Y&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1zecgoQuDHy8b0PTbvhmyNZbHDvmwecq0/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento del Arroyo Torres y afluentes',
		cuenca: 'Cuenca Río Reconquista',
		municipio: 'Merlo',
		entidad: 'Cooperativa de Trabajo Mi Cielo Ltda.',
		movimientoSocial: 'FECOOPBA',
		expediente: 'EX-2024-09736374-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-564-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Antonella Morelli',
		responsableCarga: 'Mayra Guevara',
		trabajadores: '30',
		metros: '6665',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1nIrTv62UAexj3AS3ajEMpM8EC7zArSg&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1zF-zaJ6-5wjiOXFFA_wrdXDWwx-c_PjP/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento de los Arroyos Villanueva y Los Perros y los Canales 25 de Mayo, Acoyte y Gálvez González',
		cuenca: 'Cuenca Río Reconquista',
		municipio: 'Moreno',
		entidad: 'Cooperativa de Trabajo Ayelén Ltda.',
		movimientoSocial: 'Movimiento Evita',
		expediente: 'EX-2024-09416127-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-599-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Antonella Morelli',
		responsableCarga: 'Mayra Guevara',
		trabajadores: '30',
		metros: '9600',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1oz77jXM-dVvhdThDzasXDE_nZIPjOKY&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1DZBVxfESo0HQh2xKXa55TJeCigj0SdAT/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento del Arroyo Burgueño y afluentes',
		cuenca: 'Cuenca Río Luján',
		municipio: 'Pilar',
		entidad: 'Cooperativa de Trabajo Construyendo Patria Ltda.',
		movimientoSocial: 'Movimiento Evita',
		expediente: 'EX-2024-10212631-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-582-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Juan Maglione',
		responsableCarga: 'Juan Barroca',
		trabajadores: '25',
		metros: '6150',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=11Ky_DFrBltNcZOwJCRruvFtBEZST62Y&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1bilv0a_I2jj5VYXB6L_OzhIFvEMSO8f3/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento de los Afluentes del Río Luján en Pilar',
		cuenca: 'Cuenca Río Luján',
		municipio: 'Pilar',
		entidad: 'Cooperativa de Trabajo Lu.tra Ltda.',
		movimientoSocial: 'Quebracho',
		expediente: 'EX-2024-09428485-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-597-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Juan Maglione',
		responsableCarga: 'Juan Barroca',
		trabajadores: '20',
		metros: '4500',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1TBZctvsHZYelk0Yy393JIvIohs9oGTw&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1Ua8x6zAb5SSUpcOBhtTaIrFY3xYAgDfl/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento de los Arroyos De Vicenzo y Pinazo',
		cuenca: 'Cuenca Río Luján',
		municipio: 'Pilar',
		entidad: 'Cooperativa de Trabajo Rocío Ltda.',
		movimientoSocial: 'Corriente Nacional y Popular',
		expediente: 'EX-2024-09880891-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-613-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Juan Maglione',
		responsableCarga: 'Juan Barroca',
		trabajadores: '25',
		metros: '4500',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1nsHUdAdfjs2A7a1aTmp74ZRD3LSWaP8&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1akM2lLnZDWHN7KiAtsarNGbBEROq73-P/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento de los Arroyos La Verde y Miriñay y su Afluente',
		cuenca: 'Cuenca Río Luján',
		municipio: 'Pilar',
		entidad: 'Cooperativa de Trabajo Rocío Ltda.',
		movimientoSocial: 'Corriente Nacional y Popular',
		expediente: 'EX-2024-09880635-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-600-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Juan Maglione',
		responsableCarga: 'Juan Barroca',
		trabajadores: '30',
		metros: '9000',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=14LL2Xfh4gDxTpzWZw3o6s9EBlB9r2q8&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1XGo7ZKUTBsiIVHYg8tas3LE25s1HWHEE/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento de los canales Monterrey y Doña Iris',
		cuenca: 'Cuenca Río Luján',
		municipio: 'Pilar',
		entidad: 'Cooperativa de Trabajo Rocío Ltda.',
		movimientoSocial: 'Corriente Nacional y Popular',
		expediente: 'EX-2024-09880334-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-573-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Juan Maglione',
		responsableCarga: 'Juan Barroca',
		trabajadores: '25',
		metros: '6630',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1Q6wiJ_z_YtubGhzo6Pq1iOuNoXjkvjA&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1A67ByDzpqBHjo0NCMzG5fJr8XHTvjn8R/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento del Arroyo Toro',
		cuenca: 'Cuenca Río Luján',
		municipio: 'Pilar',
		entidad: 'Cooperativa de Trabajo Tratado del Pilar 2 Ltda.',
		movimientoSocial: 'Independiente',
		expediente: 'EX-2024-09680819-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-572-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Juan Maglione',
		responsableCarga: 'Juan Barroca',
		trabajadores: '25',
		metros: '5700',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1IU8myHYsrW1o0mRmocmlQbYuotSPu-A&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1Kc7EcMeisxuiu5dYnTa-Pz42dii2V7rL/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento del Canal 1, afluente Don Eduardo y zanjones del Barrio Panamérica',
		cuenca: 'Cuenca Río Samborombón',
		municipio: 'Presidente Perón',
		entidad: 'Cooperativa de Trabajo Presidente Perón Ltda.',
		movimientoSocial: 'Movimiento Evita',
		expediente: 'EX-2024-08785199-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-612-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Antonella Morelli',
		responsableCarga: 'Julia Palacio',
		trabajadores: '30',
		metros: '5900',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1ZkDRGSyt-KDPG2W4jMw6KG6jU8XqKdk&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1FRU3yEWnlmkwuxhAJUjahHjMw7peo_6m/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento del Arroyo Giménez y su aliviador y los canales IMPA y Monteagudo',
		cuenca: 'Área de bañados',
		municipio: 'Quilmes',
		entidad: 'Cooperativa de Trabajo El Ombú Ltda.',
		movimientoSocial: 'Movimiento Evita',
		expediente: 'EX-2024-09439328-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-748-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Daniel Amarilla',
		responsableCarga: 'Silvia Guitián',
		trabajadores: '35',
		metros: '6000',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1Qinff9p-2DX-9ECUBVpPvHunmVCPV7U&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1MhFfUFogdOKRuPQF5zFOmaRCzM3MN8kJ/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento del Arroyo Las Piedras desde Comandante Franco hasta Rodolfo López',
		cuenca: 'Cuenca Arroyo San Francisco - Las Piedras',
		municipio: 'Quilmes',
		entidad: 'Cooperativa de Trabajo Evita Compañera Ltda.',
		movimientoSocial: 'Independiente',
		expediente: 'EX-2024-09501198-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-571-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Daniel Amarilla',
		responsableCarga: 'Silvia Guitián',
		trabajadores: '35',
		metros: '1750',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=17j_mm-VBB53P-Z2RPsl-wunujza8VTo&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1a0ZL60BH2EfMac-VSvHeN1fi4IkzKh4A/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento del Arroyo Las Piedras desde Rodolfo López hasta C.816',
		cuenca: 'Cuenca Arroyo San Francisco - Las Piedras',
		municipio: 'Quilmes',
		entidad: 'Cooperativa de Trabajo Evita Compañera Ltda.',
		movimientoSocial: 'Independiente',
		expediente: 'EX-2024-09501137-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-586-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Daniel Amarilla',
		responsableCarga: 'Silvia Guitián',
		trabajadores: '35',
		metros: '1570',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1a_WDbvXocoOE3zcpMHgJZa17VPVpJZQ&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/18WE68MQTQWbWAMx1C8WPGz_0BU9uNQhK/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento del Arroyo San Francisco desde su confluencia con el Arroyo Santo Domingo hasta Av. Zapiola',
		cuenca: 'Cuenca Arroyo San Francisco - Las Piedras',
		municipio: 'Quilmes',
		entidad: 'Cooperativa de Trabajo Evita Compañera Ltda.',
		movimientoSocial: 'Independiente',
		expediente: 'EX-2024-09589639-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-594-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Daniel Amarilla',
		responsableCarga: 'Silvia Guitián',
		trabajadores: '35',
		metros: '1850',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1TgvfSACqKfYriVnloZM4K8Cj5lFPcGg&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/14vSMZ-EF_4fhF_24LG8hUbWhYouSo0Q7/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento de la Cava y Canal de desagüe en Barrio Itati',
		cuenca: 'Cuenca Arroyo San Francisco - Las Piedras',
		municipio: 'Quilmes',
		entidad: 'Cooperativa de Trabajo Fuerzas del Alma Ltda.',
		movimientoSocial: 'FECOOPBA',
		expediente: 'EX-2024-17913483-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-794-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Daniel Amarilla',
		responsableCarga: 'Silvia Guitián',
		trabajadores: '30',
		metros: '1000',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1Ih6pllU2X1DmYh4h5eZVTvIw3UsO4M4&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1pZTjNKzvK2bw6TO7EroxhEeBfZAvywmE/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento de los Arroyos Santo Domingo y Las Piedras aguas abajo',
		cuenca: 'Cuenca Arroyo San Francisco - Las Piedras',
		municipio: 'Quilmes',
		entidad: 'Cooperativa de Trabajo Fuerzas del Alma Ltda.',
		movimientoSocial: 'FECOOPBA',
		expediente: 'EX-2024-09883368-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-604-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Daniel Amarilla',
		responsableCarga: 'Silvia Guitián',
		trabajadores: '30',
		metros: '1700',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1b11Rc1mDtKXxVldp5B7rsTDEUqlVZ1s&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1lD3-vANU8KoZTF8CEjCwiy5KnIEtrz9p/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento del Arroyo San Francisco entre 888 y Tte. Gral. Donato Álvarez',
		cuenca: 'Cuenca Arroyo San Francisco - Las Piedras',
		municipio: 'Quilmes',
		entidad: 'Cooperativa de Trabajo Fuerzas del Alma Ltda.',
		movimientoSocial: 'FECOOPBA',
		expediente: 'EX-2024-10841177-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-593-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Daniel Amarilla',
		responsableCarga: 'Silvia Guitián',
		trabajadores: '30',
		metros: '2400',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1xCPCmKfDZQrC8C1epLGBKSLiTThYgSM&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1efwteCGq1We22WuHaUmBLiqDguQH1Vyp/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento del Arroyo San Francisco, desde Av. Zapiola hasta calle 888',
		cuenca: 'Cuenca Arroyo San Francisco - Las Piedras',
		municipio: 'Quilmes',
		entidad: 'Cooperativa de Trabajo La Gaviota Ltda.',
		movimientoSocial: 'FECOOPBA',
		expediente: 'EX-2024-08754699-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-638-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Daniel Amarilla',
		responsableCarga: 'Silvia Guitián',
		trabajadores: '30',
		metros: '2330',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1hpEhLV4TWNv5AFJ47KLhXUT8nJnODCM&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1J5eiWlQljOj2iAyL9DgUqHK5A1XR7SUg/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento de los Canales paralelos a Ruta Nacional N°197 y Ramal Tigre',
		cuenca: 'Cuenca Río Reconquista',
		municipio: 'San Fernando',
		entidad: 'Cooperativa de Trabajo Rocío Ltda.',
		movimientoSocial: 'Corriente Nacional y Popular',
		expediente: 'EX-2024-09880089-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-615-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Juan Maglione',
		responsableCarga: 'Juan Barroca',
		trabajadores: '25',
		metros: '2830',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1tmM1IAfQh0H-9nP7VZVVsuZHrMyCL1c&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1XFlAU4ZyMoRm9jqYv5wiv-m7W2OxciXM/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento de los Canales en San Isidro',
		cuenca: 'Cuenca Río Reconquista',
		municipio: 'San Isidro',
		entidad: 'Cooperativa de Trabajo Rocío Ltda.',
		movimientoSocial: 'Corriente Nacional y Popular',
		expediente: 'EX-2024-09879790-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-619-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Juan Maglione',
		responsableCarga: 'Juan Barroca',
		trabajadores: '25',
		metros: '4300',
		href: 'https://www.google.com/maps/d/u/0/embed?mid=19KeNyCqe1lGwQHCXkWX3eQr4okKyZTc&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1mCgTqbhIZ0qZjwr9-iOKdcxPdwbxBV84/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento de los Canales Manuel Fraga y Bragado y sus afluentes',
		cuenca: 'Cuenca Río Reconquista',
		municipio: 'San Miguel',
		entidad: 'Cooperativa de Trabajo Cielos Abiertos Ltda.',
		movimientoSocial: 'Independiente',
		expediente: 'EX-2024-09415367-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-611-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Juan Maglione',
		responsableCarga: 'Iván Orellana',
		trabajadores: '25',
		metros: '4400',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=17A_ICRevoHroL87s61g4DdUXq0J2ISQ&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1ZxwsJAiqZyVe2KA83qcEWvXt2oTdVQ9N/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento de los Canales Pascuala Cueto, Luis Viale y afluente del Arroyo los Berros',
		cuenca: 'Cuenca Río Reconquista',
		municipio: 'San Miguel',
		entidad: 'Cooperativa de Trabajo Latinoamericana Ltda.',
		movimientoSocial: 'Independiente',
		expediente: 'EX-2024-09478800-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-585-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Juan Maglione',
		responsableCarga: 'Iván Orellana',
		trabajadores: '25',
		metros: '3620',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1W6t6Pr5qXlAWlI9e9Y67ESq72Qvu3nY&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1JBPRRMab8kDZA00CrPw3HpMm2haSeyLD/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento del Arroyo Los Berros',
		cuenca: 'Cuenca Río Reconquista',
		municipio: 'San Miguel',
		entidad: 'Cooperativa de Trabajo Latinoamericana Ltda.',
		movimientoSocial: 'Independiente',
		expediente: 'EX-2024-09479809-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-601-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Juan Maglione',
		responsableCarga: 'Iván Orellana',
		trabajadores: '25',
		metros: '4800',
		hrefMap: 'https://www.google.com/maps/d/embed?mid=14qM7xPLml1apEIuqjVby_qNaE-zoiYk&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1zk1EN6mD3kHNwUU-KdWTEjfZHedQ1tkc/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento del margen noroeste del Río Reconquista',
		cuenca: 'Cuenca Río Reconquista',
		municipio: 'San Miguel',
		entidad: 'Cooperativa de Trabajo Luchar es Crecer Ltda.',
		movimientoSocial: 'Independiente',
		expediente: 'EX-2024-09683744-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-617-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Juan Maglione',
		responsableCarga: 'Iván Orellana',
		trabajadores: '25',
		metros: '4620',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1AIF6bDpMERMQDunukOlY2oIVHG3nAgA&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1lrrnVSOlq_Wws8THzpQQOZHVrWPXrYDH/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento de los afluentes del Arroyo Ramallo',
		cuenca: 'Cuenca Arroyo Ramallo',
		municipio: 'San Nicolás',
		entidad: 'Cooperativa de Trabajo Liderazgo Ltda.',
		movimientoSocial: 'FECOOPBA',
		expediente: 'EX-2024-10227447-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-596-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Darío Astegiano',
		responsableCarga: 'Victor Banegas',
		trabajadores: '25',
		metros: '10620',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1z1Mo-83ogO-SfYoBDRKeIBSvkt_pNvU&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/15doQVKeMSWfeU1E-9Ig3mBWwqyqs5epQ/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento de los canales Paraguay, Alberdi y de zona este',
		cuenca: 'Cuenca Arroyo del Medio',
		municipio: 'San Nicolás',
		entidad: 'Cooperativa de Trabajo Liderazgo Ltda.',
		movimientoSocial: 'FECOOPBA',
		expediente: 'EX-2024-10225577-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-623-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Darío Astegiano',
		responsableCarga: 'Victor Banegas',
		trabajadores: '20',
		metros: '6900',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=136CMfukHJuTH-JNsrDZQO-kzhuKms_k&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/18PoSErsHqMcIG2SndN1pTISoFFD34NDi/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento de los Arroyos Langueyú, La Cascada y San Gabriel, Ramal H y áreas de regulación',
		cuenca: 'Cuenca Río Salado',
		municipio: 'Tandil',
		entidad: 'Cooperativa de Trabajo El Laurel Ltda.',
		movimientoSocial: 'Movimiento Evita',
		expediente: 'EX-2024-09283740-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-570-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Pablo Steinbach',
		responsableCarga: 'Pablo Steinbach',
		trabajadores: '30',
		metros: '8090',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1SPHaWRw_cA_fl7QhFMnzi21Vm_l7cpI&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1Nr7-FvxNIpkz6J7EiFEWUDvz-rBobFLf/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento del Canal El Dorado, Arroyo Lola y zanjas del Barrio Las Mascotas',
		cuenca: 'Cuenca Río Luján',
		municipio: 'Tigre',
		entidad: 'Cooperativa de Trabajo La Plebeya Ltda.',
		movimientoSocial: 'Quebracho',
		expediente: 'EX-2024-10222698-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-581-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Darío Astegiano',
		responsableCarga: 'Victor Banegas',
		trabajadores: '25',
		metros: '4850',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1Mqss6nUvfrfV9kKEPEjqr0Zf22KZS_c&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1_MUJFsQeAaFVHbYLivbK528GbN_jul6j/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento del Arroyo Claro',
		cuenca: 'Cuenca Río Luján',
		municipio: 'Tigre',
		entidad: 'Cooperativa de Trabajo Lu.tra Ltda.',
		movimientoSocial: 'Quebracho',
		expediente: 'EX-2024-09429541-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-568-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Darío Astegiano',
		responsableCarga: 'Victor Banegas',
		trabajadores: '25',
		metros: '6050',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1wdO51u76A26baGnhgSxOP50Zu1oxJkg&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1J1atYWbJA-YQH2ANno-14zVfSliFIeR3/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento del Canal Almirante Brown y Río Reconquista',
		cuenca: 'Cuenca Río Reconquista',
		municipio: 'Tigre',
		entidad: 'Cooperativa de Trabajo Proyectando Juntos Ltda.',
		movimientoSocial: 'FECOOPBA',
		expediente: 'EX-2024-09463142-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-567-GDEBA-MIYSPGP',
		supervisorTerritorial: 'Darío Astegiano',
		responsableCarga: 'Victor Banegas',
		trabajadores: '25',
		metros: '3211',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1F6OZDLcSzFPLQl_MVRE8NCu7JoM6PJ0&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1V6rPQs3eYjgUUU6oov0paJv0_dq8oXxv/view?usp=drive_link',
	},	
		
	{	
		obra: 'Saneamiento, limpieza y mantenimiento de los Zanjones en la localidad de Zárate',
		cuenca: 'Cuenca Arroyo de la Cruz',
		municipio: 'Zárate',
		entidad: 'Cooperativa de Trabajo La Plebeya Ltda.',
		movimientoSocial: 'Quebracho',
		expediente: 'EX-2024-10222164-GDEBA-DPTLMIYSPGP',
		resolucion: 'RESO-2024-626-GDEBA-MIYSPG',
		supervisorTerritorial: 'Darío Astegiano',
		responsableCarga: 'Victor Banegas',
		trabajadores: '25',
		metros: '3940',
		hrefMap: 'https://www.google.com/maps/d/u/0/embed?mid=1AC-HY2vbDC_566Lun95o4bDzPwJy8aw&ehbc=2E312F&noprof=1',
		fichaCauce: 'https://drive.google.com/file/d/1iOdxJAgZERbsTFy4M8S40A0X5ZZNtWnR/view?usp=drive_link',
	},	
];
